[project]
name = "pytorch-runtime-cpu"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = ["torch==2.9.0", "torchvision==0.24.0", "scikit-learn>=1.7.2"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
