name: plerion

volumes:
  minio_data:
  postgres_data:
  cloudbeaver_data:
  uv_cache:
  keycloak_data:

services:
  minio:
    image: docker.io/minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: "${S3_ACCESS_KEY}"
      MINIO_ROOT_PASSWORD: "${S3_SECRET_KEY}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 1s
      retries: 60

  initialize-minio:
    image: docker.io/minio/mc:latest
    restart: "no"
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
        mc alias set local http://minio:9000 ${S3_ACCESS_KEY} ${S3_SECRET_KEY} && \
        mc mb --ignore-existing local/dev-captures && \
        mc mb --ignore-existing local/dev-reconstructions
      "
    environment:
      S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
      S3_SECRET_KEY: "${S3_SECRET_KEY}"

  minio-logger:
    image: docker.io/minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
        set -e
        mc alias set local http://minio:9000 ${S3_ACCESS_KEY} ${S3_SECRET_KEY}
        mc admin trace --verbose --all local
      "
    environment:
      S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
      S3_SECRET_KEY: "${S3_SECRET_KEY}"

  postgres:
    image: docker.io/library/postgres:16-alpine
    expose:
      - "5432"
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -q -h localhost -p 5432 -U $${POSTGRES_USER} -d postgres",
        ]
      interval: 1s
      timeout: 1s
      retries: 30

  initialize-cloudbeaver:
    build:
      dockerfile: docker/cloudbeaver-initializer/Dockerfile
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_ADMIN_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_ADMIN_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      CB_ADMIN_NAME: ${CLOUDBEAVER_ADMIN_USER}
      CB_ADMIN_PASSWORD: ${CLOUDBEAVER_ADMIN_PASSWORD}

  cloudbeaver:
    image: docker.io/dbeaver/cloudbeaver:latest
    depends_on:
      initialize-cloudbeaver:
        condition: service_completed_successfully
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    extra_hosts:
      - "host.docker.internal:host-gateway" # speeds up start up a little
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8978"]
      interval: 1s
      timeout: 1s
      retries: 90

  create-database:
    build:
      dockerfile: docker/database-manager/Dockerfile.compose
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy
      cloudbeaver:
        condition: service_healthy
    volumes:
      - cloudbeaver_data:/mnt/efs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      BACKEND: docker
      CLOUDBEAVER_SERVICE_ID: plerion-cloudbeaver-1
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_ADMIN_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_ADMIN_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
    entrypoint: >-
      uv run --no-sync python -m src.main
      --op create
      --name ${DATABASE_NAME}
      --owner-password ${DATABASE_OWNER_PASSWORD}
      --api-user-password ${DATABASE_API_USER_PASSWORD}
      --auth-user-password ${DATABASE_AUTH_USER_PASSWORD}
      --orchestration-user-password ${DATABASE_ORCHESTRATION_USER_PASSWORD}

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.5
    command:
      - start-dev
      - --import-realm
      - --health-enabled=true
    environment:
      API_HOSTNAME: ${PUBLIC_URL}
      KEYCLOAK_ACCESS_TOKEN_LIFESPAN: ${KEYCLOAK_ACCESS_TOKEN_LIFESPAN}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: ${PUBLIC_URL}/auth
      KC_HOSTNAME_ADMIN: ${PUBLIC_URL}/auth
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME_STRICT_HTTPS: true
      KC_HOSTNAME_DEBUG: true
    volumes:
      - ./docker/keycloak/realm-export:/opt/keycloak/data/import:ro
      - keycloak_data:/opt/keycloak/data

  gateway:
    build:
      dockerfile: docker/gateway/Dockerfile
    depends_on:
      - keycloak
      - api
    ports:
      - "8080:8080"

  migrate-database:
    build:
      dockerfile: docker/database-migrator/Dockerfile
    depends_on:
      create-database:
        condition: service_completed_successfully
    volumes:
      - ./:/app # needed so /app/<SCHEMA_DIR> exists in the container
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DATABASE_NAME}
      DB_USER: ${DATABASE_NAME}_owner
      DB_PASSWORD: ${DATABASE_OWNER_PASSWORD}
      DATABASE_SCHEMA_DIR: database
      # ALLOWED_HAZARDS: "DELETES_DATA,AUTHZ_UPDATE,INDEX_BUILD,INDEX_DROPPED,HAS_UNTRACKABLE_DEPENDENCIES,ACQUIRES_ACCESS_EXCLUSIVE_LOCK"
      ALLOWED_HAZARDS: "HAS_UNTRACKABLE_DEPENDENCIES"
    restart: "no"

  api:
    build:
      dockerfile: docker/api/Dockerfile
    depends_on:
      initialize-minio:
        condition: service_completed_successfully
      migrate-database:
        condition: service_completed_successfully
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: ["gpu"]
    ports:
      - "8000:8000"
      - "5679:5678"
    volumes:
      - ./docker/localizer:/app/docker/localizer
      - ./docker/api:/app/docker/api
      - ./docker/models:/app/docker/models
      - ./common:/app/common
      - uv_cache:/root/.cache/uv
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      BACKEND: docker
      KEYCLOAK_PUBLIC_HOST: ${PUBLIC_URL}/auth
      KEYCLOAK_INTERNAL_HOST: ${KEYCLOAK_INTERNAL_HOST}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      POSTGRES_HOST: ${POSTGRES_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_API_USER: ${DATABASE_NAME}_api_user
      DATABASE_AUTH_USER: ${DATABASE_NAME}_auth_user
      DATABASE_API_USER_PASSWORD: ${DATABASE_API_USER_PASSWORD}
      DATABASE_AUTH_USER_PASSWORD: ${DATABASE_AUTH_USER_PASSWORD}
      S3_ENDPOINT_URL: "http://minio:9000"
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      RECONSTRUCTIONS_BUCKET: dev-reconstructions
      LOCALIZATION_SESSION_IMAGE: plerion-localizer
      RELOAD: true
      DEBUG: ${DEBUG_API}
      DEBUG_WAIT: ${DEBUG_WAIT_API}

  orchestrator:
    build:
      dockerfile: docker/orchestrator/Dockerfile
    depends_on:
      create-database:
        condition: service_completed_successfully
    volumes:
      - ./docker/orchestrator:/app/docker/orchestrator
      - ./docker/models:/app/docker/models
      - ./common:/app/common
      - uv_cache:/root/.cache/uv
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      BACKEND: docker
      DOCKER_HOST: unix:///var/run/docker.sock
      POSTGRES_HOST: ${POSTGRES_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_NAME}_orchestration_user
      DATABASE_USER_PASSWORD: ${DATABASE_ORCHESTRATION_USER_PASSWORD}
      S3_ENDPOINT_URL: "http://minio:9000"
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      CAPTURES_BUCKET: dev-captures
      RECONSTRUCTIONS_BUCKET: dev-reconstructions
      BATCH_JOB_QUEUE: dummy
      BATCH_JOB_DEFINITION: plerion-reconstructor
      DEBUG: ${DEBUG_RECONSTRUCTION_ORCHESTRATOR}
      DEBUG_WAIT: ${DEBUG_WAIT_RECONSTRUCTION_ORCHESTRATOR}
      DEBUG_RUN_RECONSTRUCTION: ${DEBUG_RUN_RECONSTRUCTION}
      DEBUG_WAIT_RUN_RECONSTRUCTION: ${DEBUG_WAIT_RUN_RECONSTRUCTION}

  reconstructor:
    profiles: ["ephemeral"]
    build:
      dockerfile: docker/reconstructor/Dockerfile
      cache_from:
        - type=local,src=${HOME}/.buildx-cache/reconstructor
      cache_to:
        - type=local,dest=${HOME}/.buildx-cache/reconstructor,mode=max
    volumes:
      - uv_cache:/root/.cache/uv

  localizer:
    profiles: ["ephemeral"]
    build:
      dockerfile: docker/localizer/Dockerfile
      cache_from:
        - type=local,src=${HOME}/.buildx-cache/localizer
      cache_to:
        - type=local,dest=${HOME}/.buildx-cache/localizer,mode=max
    volumes:
      - uv_cache:/root/.cache/uv
