name: plerion

volumes:
  postgres_data:
  minio_data:
  api_venv:
  common_venv:
  uv_cache:
  cloudbeaver_data:


services:
  postgres:
    image: docker.io/library/postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -h localhost -p 5432 -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 1s
      timeout: 1s
      retries: 30
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  automigrate:
    build:
      context: .
      dockerfile: services/automigrate/Dockerfile
    volumes:
      - ./api:/workspace
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      PYTHONPATH: /workspace
    depends_on:
      postgres:
        condition: service_healthy

  cloudbeaver_init:
    build:
      context: ./services/cloudbeaver-init
      dockerfile: Dockerfile
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      CB_ADMIN_NAME: ${CB_ADMIN_NAME}
      CB_ADMIN_PASSWORD: ${CB_ADMIN_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  cloudbeaver:
    image: docker.io/dbeaver/cloudbeaver:latest
    ports:
      - "8978:8978"
    depends_on:
      postgres:
        condition: service_healthy
      cloudbeaver_init:
        condition: service_completed_successfully
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8978" ]
      interval: 30s
      timeout: 5s
      retries: 3

  minio:
    image: docker.io/minio/minio:latest
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: "${S3_ACCESS_KEY}"
      MINIO_ROOT_PASSWORD: "${S3_SECRET_KEY}"
      MINIO_BROWSER_REDIRECT_URL: "https://${DEVICE_NAME}-minioconsole.${DOMAIN}"
      MINIO_SERVER_URL: "https://${DEVICE_NAME}-minio.${DOMAIN}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/ready" ]
      interval: 5s
      retries: 12

  minio-reverse-proxy:
    build: ./services/minio-reverse-proxy
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      DEVICE_NAME: "${DEVICE_NAME}"
      DOMAIN: "${DOMAIN}"
    depends_on:
      - minio

  minio_init:
    image: docker.io/minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
        mc alias set local http://minio:9000 ${S3_ACCESS_KEY} ${S3_SECRET_KEY} && \
        mc mb --ignore-existing local/dev-captures
      "
    environment:
      S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
      S3_SECRET_KEY: "${S3_SECRET_KEY}"
    restart: "no"

  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    working_dir: /app
    ports:
      - "8000:8000"
      - "5678:5678"
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      BACKEND: docker
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      S3_ENDPOINT_URL: "https://${DEVICE_NAME}-minio.${DOMAIN}"
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      JOB_QUEUE_ARN: dummy
      RECONSTRUCTION_JOB_DEFINITION_ARN_PREFIX: run-reconstruction
      FEATURES_JOB_DEFINITION_ARN_PREFIX: extract-match-features
      RELOAD: ${RELOAD_API}
      DEBUG: ${DEBUG_API}
      DEBUG_WAIT: ${DEBUG_WAIT_API}
      DEBUG_RECONSTRUCTION: ${DEBUG_RECONSTRUCTION}
      DEBUG_WAIT_RECONSTRUCTION: ${DEBUG_WAIT_RECONSTRUCTION}
      DEBUG_FEATURES: ${DEBUG_FEATURES}
      DEBUG_WAIT_FEATURES: ${DEBUG_WAIT_FEATURES}
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
      minio_init:
        condition: service_completed_successfully
    volumes:
      - ./api:/app/services/api
      - ../common:/app/common
      - uv_cache:/root/.cache/uv
      - /var/run/docker.sock:/var/run/docker.sock

  run-reconstruction:
    profiles: [ "tasks" ]
    image: run-reconstruction
    build:
      context: .
      dockerfile: tasks/run-reconstruction/Dockerfile

  extract-match-features:
    profiles: [ "tasks" ]
    image: extract-match-features
    build:
      context: .
      dockerfile: tasks/extract-match-features/Dockerfile
