[project]
name = "core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "common",
    "scipy>=1.16.3",
    "opencv-python>=4.10.0",
    "faiss-cpu>=1.12.0",
    "pillow>=12.0.0",
]

[dependency-groups]
dev = ["scipy-stubs>=1.16.3.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/core"]
include = ["src/core/py.typed"]
