[project]
name = "extract-match-features"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pydantic-settings>=2.10.1"]

[dependency-groups]
dev = ["debugpy>=1.8.16"]

[tool.ruff]
extend = "../../ruff.toml"