[project]
name = "datamodels"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pydantic>=2.11.9", "sqlalchemy[asyncio]>=2.0.43"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/datamodels"]
force-include = { "src/datamodels/py.typed" = "datamodels/py.typed" }
