[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "datamodel-code-generator>=0.33.0",
  "debugpy>=1.8.16",
  "psycopg[binary]>=3.2.10",
  "pydantic>=2.11.7",
  "pyhumps>=3.8.0",
  "scipy>=1.16.2",
  "sqlacodegen>=3.1.1",
  "typer>=0.17.4",
  "watchdog>=6.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["scipy-stubs>=1.16.2.4"]
hloc = []

[tool.hatch.build.targets.wheel]
packages = ["src/sync_workspace"]

[project.scripts]
sync-workspace = "sync_workspace.main:main"

[tool.ruff]
extend = "../ruff.toml"
