[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "common",
  "debugpy>=1.8.16",
  "pydantic>=2.11.7",
  "typer>=0.17.4",
  "watchdog>=6.0.0",
]

[tool.uv.sources]
common = { path = "../common", editable = true }

[tool.ruff]
extend = "../ruff.toml"
