openapi: 3.0.3
info:
  title: Zed API
  version: 0.1.0
servers:
- url: /
paths:
  /captures/start:
    post:
      operationId: start_capture
      parameters:
      - explode: true
        in: query
        name: capture_interval
        required: false
        schema:
          nullable: true
          title: Capture Interval
          type: number
        style: form
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      summary: Start Capture
      tags:
      - Default
  /captures/stop:
    post:
      operationId: stop_capture
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Stop Capture
      tags:
      - Default
  /captures:
    get:
      operationId: get_captures
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  format: uuid
                  type: string
                title: Response Get Captures
                type: array
          description: Successful Response
      summary: Get Captures
      tags:
      - Default
  /captures/{id}:
    delete:
      operationId: delete_capture
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          title: Id
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      summary: Delete Capture
      tags:
      - Default
    get:
      operationId: download_capture_tar
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          title: Id
          type: string
        style: simple
      responses:
        "200":
          content:
            application/x-tar:
              schema:
                format: binary
                type: string
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      summary: Download Capture Tar
      tags:
      - Default
components:
  schemas:
    HTTPValidationError:
      example:
        detail:
        - msg: msg
          loc:
          - Location_inner
          - Location_inner
          type: type
        - msg: msg
          loc:
          - Location_inner
          - Location_inner
          type: type
      properties:
        detail:
          items:
            $ref: "#/components/schemas/ValidationError"
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ValidationError:
      example:
        msg: msg
        loc:
        - Location_inner
        - Location_inner
        type: type
      properties:
        loc:
          items:
            $ref: "#/components/schemas/Location_inner"
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
    Location_inner:
      anyOf:
      - type: string
      - type: integer

